---
- name: Secure Python Secrets
  hosts: all

  tasks:

    - name: Run my python script
      register: my_output
      changed_when: my_output.rc != 0
      ansible.builtin.script:
        cmd: scripts/my_secret.py

  # Using a custom credential to make this work
  # Input Configuration
  #
  # fields:
    # - id: dynatrace_api_key
    #   type: string
    #   label: Dynatrace API Token
    #   secret: true
  #
  # Injector Configuration
  #
  # env:
  #   dynatrace_api_key: '{{ dynatrace_api_key }}'

  # Don't use this

  # vars:
  #   dynatrace_api_key: !vault |
  #     $ANSIBLE_VAULT;1.1;AES256
  #     65613536376361306264333332653466616264363833316435643662313636653063666330323438
  #     6439343462346333333835663630396637373164386464630a386234633037336662623662356236
  #     30393333633430613035656439613963373262623565346331316239376238653937396666373330
  #     3066366634663535380a303331643330396333633836303432343630353234366232303864646230
  #     65316432363830323834396335366431383133303532323266613530336635626635383861326437
  #     3730656431393831386566386566373633646431633162623237
  #
  # Contents of the vault look like this:
  # 123456_secrets_are_here

  # Don't use this

  # vars_files:
  #   - files/secrets.yml
  #
  # Contents of the vault look like this:
  # dynatrace_api_key: 123456_secrets_are_here

  # environment:
  #   DYNATRACE_API_KEY: "{{ dynatrace_api_key }}"
